## Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!mkdir -p /root/.ssh/
!ls -l /root/.ssh/
!cp /content/drive/MyDrive/deploy_keys/id_ed25519* /root/.ssh/
# Add github as trusted entity
!ssh-keyscan github.com >> /root/.ssh/known_hosts
!ssh -T git@github.com
!git clone git@github.com:MysticShadow427/homo-mex-2024.git

total 0
# github.com:22 SSH-2.0-babeld-05989c77
# github.com:22 SSH-2.0-babeld-05989c77
# github.com:22 SSH-2.0-babeld-05989c77
# github.com:22 SSH-2.0-babeld-05989c77
# github.com:22 SSH-2.0-babeld-05989c77
Hi MysticShadow427/homo-mex-2024! You've successfully authenticated, but GitHub does not provide shell access.
Cloning into 'homo-mex-2024'...
remote: Enumerating objects: 146, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 146 (delta 79), reused 98 (delta 31), pack-reused 0
Receiving objects: 100% (146/146), 2.42 MiB | 17.84 MiB/s, done.
Resolving deltas: 100% (79/79), done.


In [3]:
%cd /content/homo-mex-2024

/content/homo-mex-2024


In [4]:
!pwd

/content/homo-mex-2024


## LoRA Fine Tuning

In [ ]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 2.3 MB/s eta 0:00:00


In [ ]:
!pip install peft accelerate

In [ ]:
%matplotlib notebook
!python /content/homo-mex-2024/src/train_lora_llm.py

2024-03-29 17:19:23.849788: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-29 17:19:23.849842: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-29 17:19:23.852003: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-29 17:19:25.286598: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Datasets ready

Training arguments set.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pool

In [ ]:
!mkdir /content/lora_results

In [ ]:
import shutil

source_folder = '/content/homo-mex-2024/bert-base-spanish-wwm-uncased-modified-homo-mex'
destination_folder = '/content/lora_results/tokenizer'

shutil.copytree(source_folder, destination_folder)

'/content/lora_results/tokenizer'

In [ ]:
source_folder = '/content/homo-mex-2024/bert-base-spanish-wwm-uncased-peft-homo-mex'
destination_folder = '/content/lora_results/model'
shutil.copytree(source_folder, destination_folder)

'/content/lora_results/model'

In [ ]:
!zip -r /content/result_lora_fine_tune_spanish_bert_folder_10_epochs_all_linear_adapters.zip /content/lora_results

  adding: content/lora_results/ (stored 0%)
  adding: content/lora_results/model/ (stored 0%)
  adding: content/lora_results/model/README.md (deflated 66%)
  adding: content/lora_results/model/adapter_model.safetensors (deflated 7%)
  adding: content/lora_results/model/adapter_config.json (deflated 51%)
  adding: content/lora_results/tokenizer/ (stored 0%)
  adding: content/lora_results/tokenizer/tokenizer.json (deflated 71%)
  adding: content/lora_results/tokenizer/tokenizer_config.json (deflated 75%)
  adding: content/lora_results/tokenizer/special_tokens_map.json (deflated 80%)
  adding: content/lora_results/tokenizer/vocab.txt (deflated 56%)


In [ ]:
import shutil

source_file = '/content/result_lora_fine_tune_spanish_bert_folder_10_epochs_all_linear_adapters.zip'
destination_folder = '/content/drive/MyDrive'

shutil.copy(source_file, destination_folder)


'/content/drive/MyDrive/result_lora_fine_tune_spanish_bert_folder_10_epochs_all_linear_adapters.zip'

## Full Fine Tuning

In [ ]:
%matplotlib notebook
!python /content/homo-mex-2024/src/mex_main.py --epochs 1 --learning_rate 2e-5 --batch_size 32

Some weights of BertModel were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device :  cuda

Loaded Training, validation and test dataframes

Preprocessing of Data done

Tokenizer Loaded

Some weights of BertModel were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Model Spanish BERT Loaded

Dataloaders created

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW i

In [ ]:
!zip -r /content/result_full_fine_tune_spanish_bert_folder.zip /content/homo-mex-2024/artifacts
from google.colab import files

files.download("/content/result_full_fine_tune_spanish_bert_folder.zip")


  adding: content/homo-mex-2024/artifacts/ (stored 0%)
  adding: content/homo-mex-2024/artifacts/distribution_val_track_1.png (deflated 25%)
  adding: content/homo-mex-2024/artifacts/word_lenght_dist_val_track_1.png (deflated 10%)
  adding: content/homo-mex-2024/artifacts/history.csv (deflated 53%)
  adding: content/homo-mex-2024/artifacts/best_model_state_full_fine_tune.bin (deflated 7%)
  adding: content/homo-mex-2024/artifacts/best_model_full_fine_tune.pth (deflated 7%)
  adding: content/homo-mex-2024/artifacts/word_cloud_val_track_1.png (deflated 0%)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import shutil

source_file = '/content/result_full_fine_tune_spanish_bert_folder.zip'
destination_folder = '/content/drive/MyDrive'

shutil.copy(source_file, destination_folder)


'/content/drive/MyDrive/result_full_fine_tune_spanish_bert_folder.zip'

## XgBoost and Sentence Embeddings

In [5]:
!pip install optuna xgboost imblearn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 379.9/379.9 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.4/233.4 kB 20.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 9.0 MB/s eta 0:00:00


In [9]:
!python /content/homo-mex-2024/src/mex_train_xgboost.py --embeddings 'spanish-bert' --augmentation 'adasyn'

Starting model training...

Predictions :
              precision    recall  f1-score   support

           0       0.92      0.85      0.88       872
           1       0.90      0.94      0.92       800
           2       0.93      0.97      0.95       900

    accuracy                           0.92      2572
   macro avg       0.92      0.92      0.92      2572
weighted avg       0.92      0.92      0.92      2572

Confusion Matrix : 
 [[738  83  51]
 [ 37 753  10]
 [ 23   2 875]]
Figure(640x480)
Accuracy :  0.9199066874027994

Precision :  0.9201542221408168

Recall :  0.9199066874027994

F-1 :  0.9191586583177385
XGBoost classifier saved successfully.
